# Generated by Django 3.1.7 on 2021-04-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='name',
            field=models.CharField(default='car dealer', max_length=25),
        ),
    ]
