# Generated by Django 3.1.7 on 2021-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproperty',
            name='engine_type',
            field=models.CharField(choices=[('e', 'electrical'), ('i', 'internal combustion engine')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='carproperty',
            name='fuel_type',
            field=models.CharField(choices=[('g', 'gasoline'), ('d', 'diesel'), ('e', 'electrical'), ('o', 'another type of fuel')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='carproperty',
            name='gear_case',
            field=models.CharField(choices=[('m', 'mechanical transmission'), ('a', 'automatic transmission'), ('v', 'variator transmission')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='carproperty',
            name='population_type',
            field=models.CharField(choices=[('s', 'sedan'), ('u', 'universal'), ('v', 'SUV'), ('a', 'cabriolet'), ('c', 'coupe'), ('t', 'truck'), ('o', 'other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='carproperty',
            name='status',
            field=models.CharField(choices=[('a', 'available'), ('n', 'not available')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('o', 'open'), ('c', 'close')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='picture',
            name='position',
            field=models.CharField(choices=[('f', 'front view'), ('b', 'back view'), ('l', 'left view'), ('r', 'right view'), ('i', 'interior view'), ('g', 'general view')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture'),
        ),
    ]
