# Generated by Django 3.1.7 on 2021-04-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210413_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='cars.car'),
        ),
    ]
