# Generated by Django 3.1.7 on 2021-04-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210417_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car'),
        ),
    ]
