# Generated by Django 3.1.7 on 2021-04-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210418_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='url',
            new_name='picture',
        ),
    ]
