# Generated by Django 3.1.7 on 2021-04-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210420_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
