# Generated by Django 3.1.7 on 2021-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproperty',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
