# Generated by Django 3.1.7 on 2021-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210427_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carproperty',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='carproperty',
            name='views',
        ),
        migrations.AddField(
            model_name='car',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
