# Generated by Django 3.1.7 on 2021-04-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20210427_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
