"""Initial revision

Revision ID: 4fef86c6d6aa
Revises:
Create Date: 2021-03-11 19:40:59.152841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fef86c6d6aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'students',
        sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('enroll', mysql.INTEGER(display_width=11), nullable=True),
        sa.Column('personal_info', sa.JSON(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
